Criada as entidades Equipamento, Usuario e Emprestimo.
Winiast/Projeto-Integrador-OO pull request #8
Opened 2023-01-28 00:53 UTC by Driinho

[ ] Criada a entidade Equipamento.
[ ] Criada a entidade Usuario.
[ ] Criada a entidade Emprestimo.

2023-01-28 01:51 UTC, Winiast requested changes
Apenas arrumar para adicionar a quantidade de equipamentos.

2023-01-28 01:51 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Equipamento.java
> +
É necessário adicionar a quantidade.

2023-01-28 01:51 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Equipamento.java
> +    }
Adicionar campo de quantidade

2023-01-28 18:30 UTC, Winiast requested changes
Mudanças interessantes.

2023-01-28 18:30 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Emprestimo.java
> +    private boolean status;
Pode ser adicionado um campo de observação aqui! Por exemplo um String observação.

2023-01-28 18:30 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Emprestimo.java
> +    private boolean status;
Talvez seja interessante adicionar o esporte invés do Equipamento e ligando os Equipamentos ao esporte  assim criando conjuntos.

2023-01-28 18:30 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Esporte.java
>      private boolean status;
Adicionar um campo de Equipamento no esporte seria interessante.

2023-01-28 18:30 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Equipamento.java
> +    private LocalDateTime atualizadoEm;
Vamos colocar descrição, para caso a pessoa queira falar que está com algum problema.

2023-01-28 18:30 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Equipamento.java
> +    private LocalDateTime atualizadoEm;
Além de descrição criar uma propriedade Estado, com 4 escolhas, Excelente, Bom, Ruim, Péssimo

2023-01-28 18:30 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Equipamento.java
> +    private LocalDateTime atualizadoEm;
E uma propriedade valor estimado, para colocar o valor do equipamento.

2023-01-29 01:20 UTC, Driinho commented on src/main/java/ifpr/pgua/eic/models/entity/Equipamento.java
> +    private LocalDateTime atualizadoEm;
[refact]: De acordo com oq foi conversado fiz as devidas alterações.

2023-01-29 01:20 UTC, Driinho commented on src/main/java/ifpr/pgua/eic/models/entity/Esporte.java
>      private boolean status;
[reaft]: De acordo com oq foi conversado fiz as devidas alterações.

2023-01-29 01:21 UTC, Driinho commented on src/main/java/ifpr/pgua/eic/models/entity/Emprestimo.java
> +    private boolean status;
[refact]: De acordo com oq foi conversado fiz as devidas alterações.

2023-01-29 01:21 UTC, Driinho commented on src/main/java/ifpr/pgua/eic/models/entity/Equipamento.java
> +
Corrigido!

2023-01-29 02:02 UTC, Winiast requested changes
Alteração no dataEmpréstimo necessária.

2023-01-29 02:02 UTC, Winiast commented on src/main/java/ifpr/pgua/eic/models/entity/Emprestimo.java
>      private LocalDateTime dataEmprestimo;
Podemos colocar como dataDevoluçãoEmpréstimo.

2023-01-29 02:04 UTC, Driinho commented on src/main/java/ifpr/pgua/eic/models/entity/Emprestimo.java
>      private LocalDateTime dataEmprestimo;
Corrigido!

2023-01-29 02:16 UTC, Winiast approved these changes
Aprovado!

2023-01-29 02:17 UTC, merged